package com.test.db.test_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ClienteBase PLEASE EDIT ../Cliente.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Cliente object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.test.db.test_db.entity.Cliente;

public class ClienteBase implements RowMapper<Cliente>{
	
	private Long _id;
	
	// Attributes
    private String Citta;
    private String Indirizzo;
    private String Nazione;
    private String Provincia;
    private String RagioneSociale;
	
	
	
	@Override
	public Cliente mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Cliente obj = new Cliente();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setCitta(rs.getString("Citta"));
			obj.setIndirizzo(rs.getString("Indirizzo"));
			obj.setNazione(rs.getString("Nazione"));
			obj.setProvincia(rs.getString("Provincia"));
			obj.setRagioneSociale(rs.getString("RagioneSociale"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getCitta() {
		return Citta;
	}


	public void setCitta(String Citta) {
		this.Citta = Citta;
	}
	public String getIndirizzo() {
		return Indirizzo;
	}


	public void setIndirizzo(String Indirizzo) {
		this.Indirizzo = Indirizzo;
	}
	public String getNazione() {
		return Nazione;
	}


	public void setNazione(String Nazione) {
		this.Nazione = Nazione;
	}
	public String getProvincia() {
		return Provincia;
	}


	public void setProvincia(String Provincia) {
		this.Provincia = Provincia;
	}
	public String getRagioneSociale() {
		return RagioneSociale;
	}


	public void setRagioneSociale(String RagioneSociale) {
		this.RagioneSociale = RagioneSociale;
	}
	
    
    
    
    
}