package com.test.db.test_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ProgettoBase PLEASE EDIT ../Progetto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Progetto object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.test.db.test_db.entity.Progetto;

public class ProgettoBase implements RowMapper<Progetto>{
	
	private Long _id;
	
	// Attributes
    private BigDecimal CodiceCliente;
    private Date DataCreazione;
    private String Descrizione;
	
	// Relations Cliente
	private String Cliente;
	
	
	
	@Override
	public Progetto mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Progetto obj = new Progetto();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setCodiceCliente(rs.getDouble("CodiceCliente"));
			obj.setDataCreazione(rs.getDate("DataCreazione"));
			obj.setDescrizione(rs.getString("Descrizione"));
			
        	
        	// Relations 1:m Cliente
			obj.setCliente(rs.getString("Cliente"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public BigDecimal getCodiceCliente() {
		return CodiceCliente;
	}


	public void setCodiceCliente(BigDecimal CodiceCliente) {
		this.CodiceCliente = CodiceCliente;
	}
	public Date getDataCreazione() {
		return DataCreazione;
	}


	public void setDataCreazione(Date DataCreazione) {
		this.DataCreazione = DataCreazione;
	}
	public String getDescrizione() {
		return Descrizione;
	}


	public void setDescrizione(String Descrizione) {
		this.Descrizione = Descrizione;
	}
	
    
    // Relations 1:m Cliente
	public String getCliente() {
		return Cliente;
	}

	public void setCliente(String Cliente) {
		this.Cliente = Cliente;
	}
    
    
    
    
}