/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE progettoBaseService PLEASE EDIT ../progetto.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Progetto } from '../../domain/test_db/progetto';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Progetto.service.ts
 */

/*
 * SCHEMA DB Progetto
 *
	{
		CodiceCliente: {
			type: 'Decimal',
			required : true
		},
		DataCreazione: {
			type: 'Date',
			required : true
		},
		Descrizione: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Cliente: {
			type: Schema.ObjectId,
			ref : "Progetto"
		},
	}
 *
 */
@Injectable()
export class ProgettoBaseService {

    contextUrl: string = environment.endpoint + '/progetto';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ProgettoService.findByCliente
    *   @description CRUD ACTION findByCliente
    *   @param Objectid key Id of model to search for
    *
    */
    findByCliente(id: string): Observable<Progetto[]> {
        return this.http
            .get<Progetto[]>(this.contextUrl + '/findByCliente/' + id)
            .pipe(
                map(response => response)
            );
    }


    // Custom APIs

}
